### ISSUE TITLE
Publication about the "DDPG w/ multiple Actor-Critic pairs" approach?

### ISSUE THREAD

**Issue by MasterScrat** [mattiasljungstrom/learningtorun_2018#1]
Hello Mattias, I'm curious if DDPG with multiple AC heads is a published approach, or if you came up with it? I would be curious to read more about it.

**Comment by mattiasljungstrom** [comment]
There are other similar setups, but I haven't seen anyone exactly like this. It's often called actor-critic ensemble, or multiple-heads in other papers. 

There is also the TD3 approach, which has two Q functions using the minimal value:
https://spinningup.openai.com/en/latest/algorithms/td3.html

**Comment by MasterScrat** [comment]
Great, thanks a lot!
